
name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: verify docker
        run: |
          docker --version
          node -v
          npm -v
          git --version
          

      - uses: actions/checkout@v5

      - name: Run a multi-line script
        run: ls -l

  job-2:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: ls -l