
name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: verify docker
        run: |
          docker --version

      - name: Run a multi-line script
        run: ls -l

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Run a multi-line script
        run: ls -l

  job-3:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Run a multi-line script
        run: ls -l

  job-4:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: ls -l

  job-5:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: ls -l